output "argocd_namespace" {
  description = "Namespace ArgoCD runs in. Useful for kubectl port-forward / debugging."
  value       = kubernetes_namespace.argocd.metadata[0].name
}

output "argocd_chart_version" {
  description = "Helm chart version installed. Surfaced so a future Terratest can assert the deployed version matches expectations."
  value       = helm_release.argocd.version
}

output "cluster_secret_name" {
  description = "Name of the ArgoCD cluster Secret registering this cluster for the ApplicationSet generator. Equal to the EKS cluster name."
  value       = kubernetes_secret.cluster.metadata[0].name
}

output "initial_admin_password_command" {
  description = "Shell command to retrieve the initial admin password generated by the ArgoCD chart. Run once after apply; rotate by deleting the argocd-initial-admin-secret Secret."
  value       = "kubectl -n ${kubernetes_namespace.argocd.metadata[0].name} get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d"
}

output "port_forward_command" {
  description = "Shell command to reach the ArgoCD UI locally. Server runs as ClusterIP; deliberate for the portfolio (no public LB)."
  value       = "kubectl -n ${kubernetes_namespace.argocd.metadata[0].name} port-forward svc/argocd-server 8080:443"
}
