# Shipped so `terraform validate` works on this module standalone in CI
# (-backend=false, no Terragrunt). root.hcl's generated versions.tf overwrites
# this at instantiation (if_exists = "overwrite"); the constraint here only
# governs the standalone-validate path. `random` is declared because the Redis
# AUTH token is generated by random_password.
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.51"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}
