locals {
  # Hierarchical, env-scoped secret name. A standalone demo credential,
  # deliberately namespaced away from the real Aurora-managed secret the data tier
  # writes so the two never collide. The region is implied (secrets are
  # regional); env in the path keeps dev and prod distinct and self-describing.
  demo_secret_name = "eks-platform/${var.environment}/demo-app/credentials"
}

# Demonstration application credential.
#
# recovery_window_in_days = 0 makes teardown symmetric with apply: the default
# 7-30 day recovery window only SCHEDULES deletion, and a re-apply inside that
# window fails with "secret scheduled for deletion". Zero-window deletes
# immediately, matching bootstrap's force_destroy = true under the
# build -> screenshot -> destroy lifecycle.
resource "aws_secretsmanager_secret" "demo" {
  name                    = local.demo_secret_name
  description             = "Demonstration app credential for the IRSA/ASCP mount demo. Generated value, never committed."
  kms_key_id              = aws_kms_key.app_secrets.arn
  recovery_window_in_days = 0
}

# The value is generated, never hand-typed or committed. It lives only in
# Terraform state (the private, encrypted state bucket). A real application
# secret would be seeded out-of-band or rotated by Secrets Manager rather than
# generated by the same configuration that grants read access — called out in
# the README.
resource "random_password" "demo" {
  length = 32
  # Exclude characters that complicate shell/JSON handling in the demo without
  # materially reducing entropy at length 32.
  override_special = "!#%*-_=+"
}

resource "aws_secretsmanager_secret_version" "demo" {
  secret_id = aws_secretsmanager_secret.demo.id
  secret_string = jsonencode({
    username = "demo_app"
    password = random_password.demo.result
  })
}
